export const categories = [
    { title: "Linear", value: "linear" },
    { title: "Inverse", value: "inverse" },
    { title: "Spot", value: "spot" },
];

export const pairs = [
    { title: "BTCUSDT", value: "BTCUSDT" },
    { title: "ETHUSDT", value: "ETHUSDT" },
];

export const intervals = [
    { title: "1m", value: "1" },
    { title: "3m", value: "3" },
    { title: "5m", value: "5" },
    { title: "15m", value: "15" },
    { title: "30m", value: "30" },
    { title: "60m", value: "60" },
    { title: "120m", value: "120" },
    { title: "240m", value: "240" },
    { title: "360m", value: "360" },
    { title: "720m", value: "720" },
    { title: "1D", value: "D" },
    { title: "1W", value: "W" },
    { title: "1M", value: "M" },
];

export const indicators = {
    Trend: [
        { title: "Absolute Price Oscillator (APO)", value: "APO" },
        { title: "Aroon Indicator", value: "AROON" },
        { title: "Balance of Power (BOP)", value: "BOP" },
        { title: "Chande Forecast Oscillator (CFO)", value: "CFO" },
        { title: "Commodity Channel Index (CCI)", value: "CCI" },
        { title: "Double Exponential Moving Average (DEMA)", value: "DEMA" },
        { title: "Exponential Moving Average (EMA)", value: "EMA" },
        { title: "Mass Index (MI)", value: "MI" },
        { title: "Moving Average Convergence Divergence (MACD)", value: "MACD" },
        { title: "Moving Max (MMAX)", value: "MMAX" },
        { title: "Moving Min (MMIN)", value: "MMIN" },
        { title: "Moving Sum (MSUM)", value: "MSUM" },
        { title: "Parabolic SAR (PSAR)", value: "PSAR" },
        { title: "Qstick", value: "QSTICK" }, 
        { title: "Random Index (KDJ)", value: "KDJ" },
        { title: "Rolling Moving Average (RMA)", value: "RMA" },
        { title: "Simple Moving Average (SMA)", value: "SMA" },
        { title: "Since Change", value: "SC" },
        { title: "Triple Exponential Moving Average (TEMA)", value: "TEMA" },
        { title: "Triangular Moving Average (TRIMA)", value: "TRIMA" },
        { title: "Triple Exponential Average (TRIX)", value: "TRIX" },
        { title: "Typical Price", value: "TYPPRICE" },
        { title: "Volume Weighted Moving Average (VWMA)", value: "VWMA" },
        { title: "Vortex Indicator", value: "VORTEX" },
    ],
    Momentum: [
        { title: "Awesome Oscillator (AO)", value: "AO" },
        { title: "Chaikin Oscillator (CMO)", value: "CMO" },
        { title: "Ichimoku Cloud", value: "ICHIMOKU" },
        { title: "Percentage Price Oscillator (PPO)", value: "PPO" },
        { title: "Percentage Volume Oscillator (PVO)", value: "PVO" },
        { title: "Price Rate of Change (ROC)", value: "ROC" },
        { title: "Relative Strength Index (RSI)", value: "RSI" },
        { title: "Stochastic Oscillator (STOCH)", value: "STOCH" },
        { title: "Williams %R (WILLR)", value: "WILLR" },
    ],
    Volatility: [
        { title: "Acceleration Bands (AB)", value: "AB" },
        { title: "Average True Range (ATR)", value: "ATR" },
        { title: "Bollinger Bands (BB)", value: "BB" },
        { title: "Bollinger Band Width (BBW)", value: "BBW" },
        { title: "Chandelier Exit (CE)", value: "CE" },
        { title: "Donchian Channel (DC)", value: "DC" },
        { title: "Keltner Channel (KC)", value: "KC" },
        { title: "Moving Standard Deviation (MSTD)", value: "MSTD" },
        { title: "Projection Oscillator (PO)", value: "PO" },
        { title: "True Range (TR)", value: "TR" },
        { title: "Ulcer Index (UI)", value: "UI" },
    ],
    Volume: [
        { title: "Accumulation/Distribution (AD)", value: "AD" },
        { title: "Chaikin Money Flow (CMF)", value: "CMF" },
        { title: "Ease of Movement (EMV)", value: "EMV" },
        { title: "Force Index (FI)", value: "FI" },
        { title: "Money Flow Index (MFI)", value: "MFI" },
        { title: "Negative Volume Index (NVI)", value: "NVI" },
        { title: "On-Balance Volume (OBV)", value: "OBV" },
        { title: "Volume Price Trend (VPT)", value: "VPT" },
        { title: "Volume Weighted Average Price (VWAP)", value: "VWAP" },
    ]
}