import * as indicator from "indicatorts";
import { IndicatorProps } from "./types";

export const categories = [
    { title: "Linear", value: "linear" },
    { title: "Inverse", value: "inverse" },
    { title: "Spot", value: "spot" },
];

export const pairs = [
    { title: "BTCUSDT", value: "BTCUSDT" },
    { title: "ETHUSDT", value: "ETHUSDT" },
];

export const intervals = [
    { title: "1m", value: "1" },
    { title: "3m", value: "3" },
    { title: "5m", value: "5" },
    { title: "15m", value: "15" },
    { title: "30m", value: "30" },
    { title: "60m", value: "60" },
    { title: "120m", value: "120" },
    { title: "240m", value: "240" },
    { title: "360m", value: "360" },
    { title: "720m", value: "720" },
    { title: "1D", value: "D" },
    { title: "1W", value: "W" },
    { title: "1M", value: "M" },
];

export const defaultColumns = {
    timestamp: "",
    open: 0,
    high: 0,
    low: 0,
    close: 0,
    volume: 0,
}

export const indicators: IndicatorProps = {
    Trend: [
        {
            title: "Absolute Price Oscillator (APO)",
            value: "APO",
            func: indicator.apo,
            params: ["any"],
            config: { fast: 14, slow: 30 },
        },
        {
            title: "Aroon Indicator",
            value: "AROON",
            func: indicator.aroon,
            params: ["highs", "lows"],
            config: { period: 25 },
        },
        {
            title:
                "Balance of Power (BOP)",
            value: "BOP",
            func: indicator.bop,
            params: ["openings", "highs", "lows", "closings"],
            config: {},
        },
        {
            title: "Chande Forecast Oscillator (CFO)",
            value: "CFO",
            func: indicator.cfo,
            params: ["closings"],
            config: {},
        },
        {
            title: "Commodity Channel Index (CCI)",
            value: "CCI",
            func: indicator.cci,
            params: ["highs", "lows", "closings"],
            config: { period: 20 },
        },
        {
            title: "Double Exponential Moving Average (DEMA)",
            value: "DEMA",
            func: indicator.dema,
            params: ["any"],
            config: { period: 12 },
        },
        {
            title: "Exponential Moving Average (EMA)",
            value: "EMA",
            func: indicator.ema,
            params: ["any"],
            config: { period: 12 },
        },
        {
            title: "Mass Index (MI)",
            value: "MI",
            func: indicator.mi,
            params: ["highs", "lows"],
            config: { emaPeriod: 9, miPeriod: 25 },
        },
        {
            title: "Moving Average Convergence Divergence (MACD)",
            value: "MACD",
            func: indicator.macd,
            params: ["closings"],
            config: { fast: 12, slow: 26, signal: 9 },
        },
        {
            title: "Moving Max (MMAX)",
            value: "MMAX",
            func: indicator.mmax,
            params: ["any"],
            config: { period: 4 },
        },
        {
            title: "Moving Min (MMIN)",
            value: "MMIN",
            func: indicator.mmin,
            params: ["any"],
            config: { period: 4 },
        },
        {
            title: "Moving Sum (MSUM)",
            value: "MSUM",
            func: indicator.msum,
            params: ["any"],
            config: { period: 4 },
        },
        {
            title: "Parabolic SAR (PSAR)",
            value: "PSAR",
            func: indicator.psar,
            params: ["highs", "lows", "closings"],
            config: { step: 0.02, max: 0.2 },
        },
        {
            title: "Qstick",
            value: "QSTICK",
            func: indicator.qstick,
            params: ["openings", "closings"],
            config: { period: 14 },
        },
        {
            title: "Random Index (KDJ)",
            value: "KDJ",
            func: indicator.kdj,
            params: ["highs", "lows", "closings"],
            config: { rPeriod: 9, kPeriod: 3, dPeriod: 3 },
        },
        {
            title: "Rolling Moving Average (RMA)",
            value: "RMA",
            func: indicator.rma,
            params: ["any"],
            config: { period: 4 },
        },
        {
            title: "Simple Moving Average (SMA)",
            value: "SMA",
            func: indicator.sma,
            params: ["any"],
            config: { period: 2 },
        },
        {
            title: "Since Change",
            value: "SC",
            func: indicator.since,
            params: ["any"],
            config: {},
        },
        {
            title: "Triple Exponential Moving Average (TEMA)",
            value: "TEMA",
            func: indicator.tema,
            params: ["any"],
            config: { period: 2 },
        },
        {
            title: "Triangular Moving Average (TRIMA)",
            value: "TRIMA",
            func: indicator.trima,
            params: ["any"],
            config: { period: 4 },
        },
        {
            title: "Triple Exponential Average (TRIX)",
            value: "TRIX",
            func: indicator.trix,
            params: ["any"],
            config: { period: 4 },
        },
        {
            title: "Typical Price",
            value: "TYPPRICE",
            func: indicator.typprice,
            params: ["highs", "lows", "closings"],
            config: {},
        },
        {
            title: "Volume Weighted Moving Average (VWMA)",
            value: "VWMA",
            func: indicator.vwma,
            params: ["closings", "volumes"],
            config: { period: 20 },
        },
        {
            title: "Vortex Indicator",
            value: "VORTEX",
            func: indicator.vortex,
            params: ["highs", "lows", "closings"],
            config: { period: 14 },
        },
    ],
    Momentum: [
        {
            title: "Awesome Oscillator (AO)",
            value: "AO",
            func: indicator.ao,
            params: ["highs", "lows"],
            config: { fast: 5, slow: 34 },
        },
        {
            title: "Chaikin Oscillator (CMO)",
            value: "CMO",
            func: indicator.cmo,
            params: ["highs", "lows", "closings", "volumes"],
            config: { fast: 3, slow: 10 },
        },
        {
            title: "Ichimoku Cloud",
            value: "ICHIMOKU",
            func: indicator.ichimokuCloud,
            params: ["highs", "lows", "closings"],
            config: { short: 9, medium: 26, long: 52, close: 26 },
        },
        {
            title: "Percentage Price Oscillator (PPO)",
            value: "PPO",
            func: indicator.ppo,
            params: ["any"],
            config: { fast: 12, slow: 26, signal: 9 },
        },
        {
            title: "Percentage Volume Oscillator (PVO)",
            value: "PVO",
            func: indicator.pvo,
            params: ["volumes"],
            config: { fast: 12, slow: 26, signal: 9 },
        },
        {
            title: "Price Rate of Change (ROC)",
            value: "ROC",
            func: indicator.roc,
            params: ["closings"],
            config: { period: 3 },
        },
        {
            title: "Relative Strength Index (RSI)",
            value: "RSI",
            func: indicator.rsi,
            params: ["closings"],
            config: { period: 14 },
        },
        {
            title: "Stochastic Oscillator (STOCH)",
            value: "STOCH",
            func: indicator.stoch,
            params: ["highs", "lows", "closings"],
            config: { kPeriod: 14, dPeriod: 3 },
        },
        {
            title: "Williams %R (WILLR)",
            value: "WILLR",
            func: indicator.willr,
            params: ["highs", "lows", "closings"],
            config: { period: 14 },
        },
    ],
    Volatility: [
        {
            title: "Acceleration Bands (AB)",
            value: "AB",
            func: indicator.ab,
            params: ["highs", "lows", "closings"],
            config: { period: 20, multiplier: 4 },
        },
        {
            title: "Average True Range (ATR)",
            value: "ATR",
            func: indicator.atr,
            params: ["highs", "lows", "closings"],
            config: { period: 14 },
        },
        {
            title: "Bollinger Bands (BB)",
            value: "BB",
            func: indicator.bb,
            params: ["closings"],
            config: { period: 20 },
        },
        // {
        //     title: "Bollinger Band Width (BBW)",
        //     value: "BBW",
        //     func: indicator.bbw,
        //     params: [],
        //     config: {},
        // },
        {
            title: "Chandelier Exit (CE)",
            value: "CE",
            func: indicator.ce,
            params: ["highs", "lows", "closings"],
            config: { period: 22 },
        },
        {
            title: "Donchian Channel (DC)",
            value: "DC",
            func: indicator.dc,
            params: ["closings"],
            config: { period: 4 },
        },
        {
            title: "Keltner Channel (KC)",
            value: "KC",
            func: indicator.kc,
            params: ["highs", "lows", "closings"],
            config: { period: 20 },
        },
        {
            title: "Moving Standard Deviation (MSTD)",
            value: "MSTD",
            func: indicator.mstd,
            params: ["any"],
            config: { period: 4 },
        },
        {
            title: "Projection Oscillator (PO)",
            value: "PO",
            func: indicator.po,
            params: ["highs", "lows", "closings"],
            config: { period: 14, smooth: 3 },
        },
        {
            title: "True Range (TR)",
            value: "TR",
            func: indicator.tr,
            params: ["highs", "lows", "closings"],
            config: {},
        },
        {
            title: "Ulcer Index (UI)",
            value: "UI",
            func: indicator.ui,
            params: ["closings"],
            config: { period: 14 },
        },
    ],
    Volume: [
        {
            title: "Accumulation/Distribution (AD)",
            value: "AD",
            func: indicator.ad,
            params: ["highs", "lows", "closings", "volumes"],
            config: {},
        },
        {
            title: "Chaikin Money Flow (CMF)",
            value: "CMF",
            func: indicator.cmf,
            params: ["highs", "lows", "closings", "volumes"],
            config: { period: 20 },
        },
        {
            title: "Ease of Movement (EMV)",
            value: "EMV",
            func: indicator.emv,
            params: ["highs", "lows", "volumes"],
            config: { period: 14 },
        },
        {
            title: "Force Index (FI)",
            value: "FI",
            func: indicator.fi,
            params: ["closings", "volumes"],
            config: { period: 13 },
        },
        {
            title: "Money Flow Index (MFI)",
            value: "MFI",
            func: indicator.mfi,
            params: ["highs", "lows", "closings", "volumes"],
            config: { period: 14 },
        },
        {
            title: "Negative Volume Index (NVI)",
            value: "NVI",
            func: indicator.nvi,
            params: ["closings", "volumes"],
            config: { start: 1000, period: 255 },
        },
        {
            title: "On-Balance Volume (OBV)",
            value: "OBV",
            func: indicator.obv,
            params: ["closings", "volumes"],
            config: {},
        },
        {
            title: "Volume Price Trend (VPT)",
            value: "VPT",
            func: indicator.vpt,
            params: ["closings", "volumes"],
            config: {},
        },
        {
            title: "Volume Weighted Average Price (VWAP)",
            value: "VWAP",
            func: indicator.vwap,
            params: ["closings", "volumes"],
            config: { period: 14 },
        },
    ]
}